testsuite: Require bitint in gcc.dg/torture/bitint-101.c
The new gcc.dg/torture/bitint-101.c test FAILs on Solaris/SPARC:

FAIL: gcc.dg/torture/bitint-101.c   -O0  (test for excess errors)
UNRESOLVED: gcc.dg/torture/bitint-101.c   -O0  compilation failed to produce executable

Excess errors:
gcc.dg/torture/bitint-101.c:4:1: sorry, unimplemented: '_BitInt(2)' is not supported on this target
gcc.dg/torture/bitint-101.c:11:3: sorry, unimplemented: '_BitInt(2)' is not supported on this target

Fixed by requiring bitint support.

Tested on sparc-sun-solaris2.11 and i386-pc-solaris2.11.

2026-07-16  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	gcc/testsuite:
	* gcc.dg/torture/bitint-101.c: Require bitint.

(cherry picked from commit 1731ba6e70ff806c209ab4d73c402257afd41768)